from cryptography.fernet import Fernet
import time
text =  input("[*] Enter the text you want to encrypt: ")
key = Fernet.generate_key()
f = Fernet(key)
encrypted_text =  f.encrypt(text.encode())
encrypted_text = encrypted_text.decode()
print ()
print(f"[*] Your encrypted text : {encrypted_text}")
print()
time.sleep(3)
print(f"[*] Your KEY: \n {(key.decode())}")
print()
time.sleep(3)
print("From this key you can decrypt the encrypted text")
file = open('key.key','wb')
file.write(key)
time.sleep(4)
print()
print("[*] Your key is stored in file 'key.key'")
print()
print("Make sure that you will keep this file safely do not Perform any other encryption operation\n before moving this key.key file into another directory as another encrption operation overwrite the new key in this file.")
